### ISSUE TITLE
What made you decide to start contributing to open source?

### ISSUE THREAD

**Issue by sindresorhus** [robbbz/ama#6]
Noticed you just joined GitHub a month ago. Just curious what made you decide to get involved.

**Comment by robbbz** [comment]
Your tweet about your AMA made me decide to ask a question, found it fun, asked some more questions, ... 

After seeing your GitHub profile (and the one from @passy @arthurvr and some other people I see oftentimes) I just started looking at what yall did and started participating in discussions and projects. That's it. Don't really know what projects I'll stick on, yet. 

If you'd be new to OSS what project would you want to get involved with?

**Comment by stoeffel** [comment]
> If you'd be new to OSS what project would you want to get involved with?

I would start with the ones you are most interested in (you mentioned purescript and ember in #7) :smile: 
Or just start something on your own.

**Comment by stoeffel** [comment]
Also see @stephenplusplus's answer https://github.com/stephenplusplus/ama/issues/17#issuecomment-118088744
