### ISSUE TITLE
Who are you?

### ISSUE THREAD

**Issue by sindresorhus** [robbbz/ama#7]
You've asked a lot of questions on my AMA. Which I appriciate. I'm curious who you are. Can you write a little bit about who you are and what you do?

**Comment by robbbz** [comment]
Good question. I'm anonymous on the internet and would like that to stay as is. Rob isn't even my real name, and you won't be able to identify my twitter account eighter, nor my location, not even my mail. 

That has good reasons though. The internet knows everything about everybody and I'm one of those people who'd like for that to change. I do live in one of the most censoring countries in the world too. Sadly.

I'm willing to write a bit about my proffesional activities though. I am mainly a JavaScript developer, and worked on a big Rails app past 5 years. Now I do only freelancing and am writing front-end apps. At the moment I am into Ember. As fun side things, every now and then I do some functional programming as a hobby. Mainly Purescript, but I'm proficient in Haskell and F#. Rust is one of those things I'd like to pick up one day too.

**Comment by sindresorhus** [comment]
:+1: In open source it doesn't matter who you are. What you do is what matters ;) Thanks again for all the AMA questions. Keep up the open source contributions and you'll soon be hooked too :p
