### ISSUE TITLE
Why do you prefer to be anonymous?

### ISSUE THREAD

**Issue by diessica** [robbbz/ama#8]
I mean, do you think that humans are that bad at all with people's information?

(Sorry if this question offends you somehow.)

**Comment by robbbz** [comment]
It's not about humans, it's about companies like Google etc.

**Comment by diessica** [comment]
There are people behind Google. That's what I meant.

Do you think Google is that bad to people?

**Comment by robbbz** [comment]
No, I don't think they're really bad. But IMHO having too much information can't be good. Definitely not for companies with a financial focus.
